project '/Users/ios5/Desktop/Alien-Man-Dos/WorkoutApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'WorkoutApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WorkoutApp

  target 'WorkoutAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Firebase/Core'
pod 'Firebase/Messaging'
  target 'WorkoutAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
